let promise_2 = new Promise(function (resolve, reject) {
//   setTimeout(() => {
//     console.log("this is before the resolve");
//     let error = false;
//     if (error == false) {
//       resolve();
//     } else {
//       reject();
//     }
//   }, 1000);
// });

// promise_2
//   .then(function () {
//     console.log("no error :-) ");
//   })
//   .catch(function () {
//     console.log("there is an error -_-");
//   });